### PR TITLE
Move _invert_no_zero to caput and add deprecation warning

### PR DESCRIPTION
**Pull request by ljgray**
Accompanies radiocosmology/caput#221

### CODE REVIEW

**Comment by jrs65** [comment]
I think this is linked to the other PR, but we should move the routine at the level of the `draco.util.tools.invert_no_zero` rather than the `_fast_tools._invert_no_zero` level.

**Comment by ljgray** [comment]
> I think this is linked to the other PR, but we should move the routine at the level of the `draco.util.tools.invert_no_zero` rather than the `_fast_tools._invert_no_zero` level.

What I'm thinking here is that we would just remove invert_no_zero from draco altogether, and this is just temporary so that anyone using it can switch to importing from caput. If you think it's fine to make a breaking change then we could just remove it altogether

**Comment by jrs65** [comment]
Agreed. But you should remove `_invert_no_zero` entirely, move the remaining functionality of `draco.util.tools.invert_no_zero` into caput, and turn `draco.util.tools.invert_no_zero` into a thin shim calling `caput.tools.invert_no_zero`.

**Comment by ljgray** [comment]
Ah, I see what you mean

**Review by jrs65 — APPROVED** [review]

**Pull request merged**
