### PR TITLE
Gain sims

### PR DESCRIPTION
**Pull request by cahofer**
I had to make an extra function _generate_gain in order to be able to do certain calls only once for phase and amplitude, specifically when doing temperature dependent gain simulations (development in ch_pipeline)

### CODE REVIEW

**Comment by cahofer** [comment]
Oh and I am not sure why it's showing changes in mapmaker, it might be because I separated some developments from this branch into a new one (mapmaker-dev)

**Comment by jrs65** [comment]
It's because you're still using the old `gain_sims` branch. Please take your new changes and apply them to a new branch directly based off `master`.

**Comment by jrs65** [comment]
Superficially your changes look good, but I'll do a proper review once you've got the branches sorted out. Thanks!

**Comment by cahofer** [comment]
Okay closing this one and making a new PR

**Pull request closed without merging**
