### PR TITLE
fix(ApplyRFIMask): don't apply mask to local array.

### PR DESCRIPTION
**Pull request by ljgray**
Trying to apply the mask to the .local_array results in an
AttribteError. This should fix the issue, although an mpiarray warning
will occur. This reverts a change made in #185

### CODE REVIEW

**Comment by jrs65** [comment]
Can you explain why the `AttributeError` happens?

**Comment by jrs65** [comment]
I don't understand it at all. If the result of `tsc.weight[:]` isn't an MPIArray then none of the code above it should work.

**Comment by ljgray** [comment]
```python
AttributeError: can't set attribute 'local_array'
```

Looking at `MPIArray`, there doesn't appear to be a setter for `.local_array`, so I think that's what throwing the `AttributeError`.

**Comment by jrs65** [comment]
Oh, then I think you just need to do `.local_array[:] *=`

**Comment by ljgray** [comment]
PR should be updated for that change.

**Review by jrs65 — APPROVED** [review]

**Comment by jrs65** [comment]
Does that change actually work? I think it might need to be `tsc.weight[:].local_array[:]`. The first slice is needed to get the MPIArray out, and then second to avoid the missing local_array setter.

**Pull request merged**
