### PR TITLE
Fixes for simulating sidereal streams

### PR DESCRIPTION
**Pull request by jrs65**

### CODE REVIEW

**Review by sjforeman — APPROVED** [review]
This conveniently addresses both items in https://github.com/radiocosmology/draco/issues/124

**Comment by jrs65** [comment]
> This conveniently addresses both items in #124

I live to serve.

**Comment by jrs65** [comment]
Actually, I'm finding some funny segfaults when running this. There seems to be a way it can index out of bounds in the Cython code that I don't quite understand at the moment.

**Comment by sjforeman** [comment]
> Actually, I'm finding some funny segfaults when running this. There seems to be a way it can index out of bounds in the Cython code that I don't quite understand at the moment.

Interesting. I ran it myself for a small non-CHIME telescope without any issues.

**Comment by jrs65** [comment]
@sjforeman the segfault was coming from the prod map coming out with an unexpected type and getting cast incorrectly. I think I've fixed that one, and any other risky cats.

**Pull request merged**
