### PR TITLE
Updates for beam measurement processing

### PR DESCRIPTION
**Pull request by tristpinsm**
- Moved beam container definitions here from `ch_pipeline`

### CODE REVIEW

**Comment by Meilingdeng** [comment]
they all look good to me, except that I do not understand the 'pol' axis, so it will be E_theta/E_phi or E_co/E_cx as the ludwig3 definition, or can be both?

**Comment by tristpinsm** [comment]
@Meilingdeng In principle it can be either. At the moment I haven't put in a place to specify the polarization axes. If we think we will be carrying around datasets with both of these conventions I can add attribute that describes which one it is. But given it is easy to convert between these two we might avoid confusion by always writing theta/phi and converting to ludwig3 when that is helpful

**Comment by tristpinsm** [comment]
another alternative would be to tie these conventions to the choice of coordinates. So if we are using celestial it is theta/phi and for telescope coordinates it could be ludwig3 for example

**Comment by Meilingdeng** [comment]
I see.. to me, I think stick to E_theta/E_phi and convert to Ludwig 3 when
necessary is good, so that no confusion and also flexible.

**Comment by jrs65** [comment]
@tristpinsm how far off do you think this is? It would be good to get the changes merged in. Particularly the work on the regridder which is useful elsewhere.

**Comment by tristpinsm** [comment]
I think this is pretty much done as far as the goal of getting holography transits regridded and packaged into beam containers go (as is https://bitbucket.org/chime/ch_pipeline/pull-requests/19/holography-transit-processing/diff). So if it looks good to you we should go ahead and merge.

**Comment by jrs65** [comment]
@tristpinsm any reason to not merge this one?

**Comment by tristpinsm** [comment]
No, nothing new. It should be ready to merge.

**Pull request merged**
